local:
  hosts:
    localhost:
      ansible_host: 127.0.0.1
      ansible_port: 22
      ansible_user: "angel"
      # Ubicación de la clave privada
      ansible_ssh_private_key_file: "id_rsa"
      # Contraseña de SUDO
      ansible_su_user: "angel"
      ansible_become_password: ""
  vars:
    ansible_python_interpreter: /usr/bin/python3
