- name: packages are up to date
  become: yes
  apt:
    upgrade: dist

- name: required repositories are present
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/ubuntu/20.04/prod focal main
    state: present
    update_cache: yes

- name: required packages are present
  become: yes
  apt:
    pkg: "dotnet-sdk-3.1"
    state: present
